# Generated by Django 4.2.11 on 2024-09-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsignalapp', '0005_remove_contact_phone_contact_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('technique', 'Problème Technique'), ('moral', ' Problèm"e morale'), ('autre', 'Autre problème')], max_length=50),
        ),
    ]
