# Generated by Django 4.2.11 on 2024-09-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsignalapp', '0006_alter_problem_firstname_alter_problem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='name',
        ),
    ]
